from flask import Flask

APP: Flask = Flask(__name__)


class HTTPCodes:
    OK = 200
    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    FORBIDDEN = 403
    NOT_FOUND = 404


class APICodes:
    SUCCESS = 0
    BAD_USERNAME_OR_PASSWORD = 1
    ACCOUNT_ALREADY_EXISTS = 2
    NO_PASSWORD_OR_USERNAME_PROVIDED = 3
    MAX_CHAR_LENGTH_EXCEEDED = 4
    NO_TOKEN_PROVIDED = 5
    INVALID_QUIZ_REQUESTED = 6
    INVALID_QUIZ_KEY = 7
    NO_QUIZ_PROVIDED = 8
    NOT_IMPLEMENTED_YET = 9
    INVALID_SPECIFIC_LOCATION_NAME = 10
